@startuml

package "Модуль хранения данных" {
component "Система авторизации"
component "Система управления файлами"
component "Система страничной\nорганизации памяти"

database "Файлы с данными" as DataFiles
database "Хранилище метаданных" as Metadata
database "Индексы" as Indexes
}

package "Модуль обработки запросов" {
component "Парсер запросов\nв синтаксическое дерево"
component "Модуль преобразования\nсинтаксического дерева\nв план исполнения запроса"
component "Оптимизатор планов\nисполнения запросов"
component "Модуль исполнения плана"
}

package "Модуль управления транзакциями" {
component "Система восстановления\nпосле перезапуска"
component "Система синхронизации"
}

"Модуль обработки запросов" --> "Модуль хранения данных"
"Модуль управления транзакциями" --> "Модуль хранения данных"
"Модуль управления транзакциями" --> "Модуль обработки запросов"

"Система управления файлами" --> DataFiles
"Система управления файлами" --> Metadata
"Система управления файлами" --> Indexes

@enduml
